language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-dashing.gemspec
- gem install sensu-plugins-dashing-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: Vf4nIZYhkl0Er7OS4zF3QzqlyGMdByFMggxWClN8qTOSlrJi++2hdeJSAgKp1YhuBwYtayCCaF1WILNc9N+W/tWvwH6R292XscZJQYt4M8tyev47Zh6e3OjhB7TxhLdc8ZUEnJgA1ooAFkCZVd+aiN6X/UlMVD0esOUkomJvgiM=
  gem: sensu-plugins-dashing
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-dashing
